{-# OPTIONS --prop --postfix-projections --safe #-}

-- The cocompleteness structure of SetoidCat: initial object, strong coproducts, ω-colimits, and
-- cocontinuous products. This is the standalone half of the factorisation — instantiating colimit-mu-types
-- against it builds μ-types of polynomial functors on setoids (the index μ-types of the Fam construction).

open import Level using (_⊔_)
open import Data.Nat using (ℕ; suc; _≤′_; ≤′-refl; ≤′-step) renaming (_⊔_ to _⊔ℕ_)
open import Data.Nat.Properties using (m≤m⊔n; m≤n⊔m; ≤⇒≤′; ≤′⇒≤; ⊔-monoˡ-≤; ⊔-monoʳ-≤)
open import Data.Product using (_,_; Σ)
open import Data.Sum using (inj₁; inj₂)
open import prop using (_,_; ∃; liftS; tt; proj₁; proj₂)
open import categories
  using (Category; HasInitial; IsInitial; HasProducts; HasStrongCoproducts)
open import functor
  using (Functor; NatTrans; Colimit; IsColimit; constF; ≃-NatTrans; HasColimits)
open import omega-chains using (ω; chain; step-cocone; cocone-step)
open import prop-setoid
  using (Setoid; IsEquivalence; 𝟘; from-𝟘; from-𝟘-unique; +-setoid; ⊗-setoid; case; inject₁; inject₂;
         rel→Setoid; EquivOf-intro; rel-preserving-func; elim-EquivOfS)
  renaming (_⇒_ to _⇒s_; _≃m_ to _≈s_)
open import setoid-cat using (SetoidCat; Setoid-products)

open Setoid
open IsEquivalence
open _⇒s_
open _≈s_

module setoid-cat-colimits where

-- Work in SetoidCat o (o ⊔ e): the colimit's generated equality lands at level o ⊔ e, so the apex only fits
-- when the equality level absorbs the carrier level. The Fam index setoids (Setoid os (os ⊔ es)) are of this form.
module _ o e where
  private
    𝒮 = SetoidCat o (o ⊔ e)
  open Category 𝒮
  open HasInitial
  open IsInitial
  open HasStrongCoproducts

  initial : HasInitial 𝒮
  initial .witness = 𝟘
  initial .is-initial .from-initial = from-𝟘
  initial .is-initial .from-initial-ext f = from-𝟘-unique from-𝟘 f

  strongCoproducts : HasStrongCoproducts 𝒮 (Setoid-products o (o ⊔ e))
  strongCoproducts .coprod = +-setoid
  strongCoproducts .in₁ = inject₁
  strongCoproducts .in₂ = inject₂
  strongCoproducts .copair = case
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = f₁≈f₂ .func-eq (w≈ , x≈)
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = g₁≈g₂ .func-eq (w≈ , y≈)
  strongCoproducts .copair-in₁ f g .func-eq (w≈ , x≈) = f .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-in₂ f g .func-eq (w≈ , y≈) = g .func-resp-≈ (w≈ , y≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = h .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = h .func-resp-≈ (w≈ , y≈)

  -- Sequential colimit of a setoid ω-chain: pairs (n , x) with x in the n-th setoid, under the equivalence
  -- generated by identifying x with its image one (or more) steps up the chain.
  ωcolimits : HasColimits ω 𝒮
  ωcolimits D = colim
    where
    module D = Functor D

    A : Set o
    A = Σ ℕ (λ n → D.fobj n .Carrier)

    R : A → A → Prop (o ⊔ e)
    R (n , x) (m , y) = ∃ (n ≤′ m) (λ p → D.fobj m ._≈_ (D.fmor p .func x) y)

    apex : Setoid o (o ⊔ e)
    apex = rel→Setoid A R

    cocone : NatTrans D (constF ω apex)
    cocone .NatTrans.transf n .func x = n , x
    cocone .NatTrans.transf n .func-resp-≈ x≈ = EquivOf-intro (≤′-refl , D.fmor-id .func-eq x≈)
    cocone .NatTrans.natural p .func-eq a≈ = EquivOf-intro (p , D.fmor p .func-resp-≈ a≈)

    mediate : (X' : Setoid o (o ⊔ e)) → NatTrans D (constF ω X') → apex ⇒s X'
    mediate X' γ = rel-preserving-func X' f base
      where
      f : A → X' .Carrier
      f (n , a) = γ .NatTrans.transf n .func a

      base : ∀ {u v} → R u v → X' ._≈_ (f u) (f v)
      base {n , a} {m , b} (p , da≈b) =
        X' .isEquivalence .trans
          (γ .NatTrans.natural p .func-eq (D.fobj n .isEquivalence .refl))
          (γ .NatTrans.transf m .func-resp-≈ da≈b)

    colim : Colimit D
    colim .Colimit.apex = apex
    colim .Colimit.cocone = cocone
    colim .Colimit.isColimit .IsColimit.colambda = mediate
    colim .Colimit.isColimit .IsColimit.colambda-cong {X'} {α} α≈β .func-eq {n , a} {m , b} u≈v =
      X' .isEquivalence .trans
        (mediate X' α .func-resp-≈ u≈v)
        (α≈β .≃-NatTrans.transf-eq m .func-eq (D.fobj m .isEquivalence .refl))
    colim .Colimit.isColimit .IsColimit.colambda-coeval X' γ .≃-NatTrans.transf-eq n .func-eq a≈ =
      γ .NatTrans.transf n .func-resp-≈ a≈
    colim .Colimit.isColimit .IsColimit.colambda-ext X' f .func-eq {n , a} u≈v = f .func-resp-≈ u≈v

  open HasProducts (Setoid-products o (o ⊔ e)) using (prod; prod-m; prod-m-cong; prod-m-comp)
  open NatTrans using (transf)

  -- Finite products preserve ω-colimits: the product of two colimits is the colimit of the product chain.
  module _ {X Y : ℕ → obj} {f : ∀ k → X k ⇒ X (suc k)} {g : ∀ k → Y k ⇒ Y (suc k)} {a b : obj}
           {cX : NatTrans (chain {𝒞 = 𝒮} X f) (constF ω a)} {cY : NatTrans (chain {𝒞 = 𝒮} Y g) (constF ω b)}
           (isX : IsColimit (chain {𝒞 = 𝒮} X f) a cX) (isY : IsColimit (chain {𝒞 = 𝒮} Y g) b cY) where
    private
      Xc  = chain {𝒞 = 𝒮} X f
      Yc  = chain {𝒞 = 𝒮} Y g
      PXY = chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k))

      CXY : Colimit PXY
      CXY = ωcolimits PXY

      canonX = ωcolimits Xc
      canonY = ωcolimits Yc

      ιX : a ⇒s canonX .Colimit.apex
      ιX = isX .IsColimit.colambda (canonX .Colimit.apex) (canonX .Colimit.cocone)

      ιY : b ⇒s canonY .Colimit.apex
      ιY = isY .IsColimit.colambda (canonY .Colimit.apex) (canonY .Colimit.cocone)

      -- Two walks with the same endpoints agree; `varying` additionally absorbs a single-step shift of
      -- the source through the chain.
      module walks (D : Functor ω 𝒮) where
        private
          module D = Functor D

        fixed : ∀ {k M N} (low : k ≤′ M) (mid : M ≤′ N) (hi : k ≤′ N) (a : D.fobj k .Carrier) →
                D.fobj N ._≈_ (D.fmor mid .func (D.fmor low .func a)) (D.fmor hi .func a)
        fixed low mid hi a =
          D.fobj _ .isEquivalence .trans
            (D.fobj _ .isEquivalence .sym (D.fmor-comp mid low .func-eq (D.fobj _ .isEquivalence .refl)))
            (D.fmor-cong tt .func-eq (D.fobj _ .isEquivalence .refl))

        varying : ∀ {k k' M N} (p : k ≤′ k') (low : k ≤′ M) (mid : M ≤′ N) (hi : k' ≤′ N)
                  {a : D.fobj k .Carrier} {a' : D.fobj k' .Carrier} →
                  D.fobj k' ._≈_ (D.fmor p .func a) a' →
                  D.fobj N ._≈_ (D.fmor mid .func (D.fmor low .func a)) (D.fmor hi .func a')
        varying p low mid hi wa =
          D.fobj _ .isEquivalence .trans
            (D.fobj _ .isEquivalence .sym (D.fmor-comp mid low .func-eq (D.fobj _ .isEquivalence .refl)))
          (D.fobj _ .isEquivalence .trans
            (D.fmor-cong tt .func-eq (D.fobj _ .isEquivalence .refl))
          (D.fobj _ .isEquivalence .trans
            (D.fmor-comp hi p .func-eq (D.fobj _ .isEquivalence .refl))
            (D.fmor hi .func-resp-≈ wa)))

      module wX = walks Xc
      module wY = walks Yc

      -- The product chain's transport is the pairing of the component transports.
      prod-walk : ∀ {m n} (qw : m ≤′ n) (a : X m .Carrier) (b : Y m .Carrier) →
                  prod (X n) (Y n) ._≈_ (PXY .Functor.fmor qw .func (a , b))
                                         (Xc .Functor.fmor qw .func a , Yc .Functor.fmor qw .func b)
      prod-walk ≤′-refl      a b = prod (X _) (Y _) .isEquivalence .refl
      prod-walk (≤′-step qw) a b .proj₁ = f _ .func-resp-≈ (prod-walk qw a b .proj₁)
      prod-walk (≤′-step qw) a b .proj₂ = g _ .func-resp-≈ (prod-walk qw a b .proj₂)

      κ-fwd : prod (canonX .Colimit.apex) (canonY .Colimit.apex) ⇒s CXY .Colimit.apex
      κ-fwd .func ((k , x) , (j , y)) =
        _ , (Xc .Functor.fmor (≤⇒≤′ (m≤m⊔n k j)) .func x , Yc .Functor.fmor (≤⇒≤′ (m≤n⊔m k j)) .func y)
      κ-fwd .func-resp-≈ {u₁ , (uj , uy)} {(vk , vx) , v₂} (liftS px , liftS qy) =
        CXY .Colimit.apex .isEquivalence .trans
          (elim-EquivOfS (CXY .Colimit.apex) (λ w → κ-fwd .func (w , (uj , uy)))
            (λ { {k , x} {k' , x'} (p , wx) →
              EquivOf-intro
                ( ≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))
                , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) _ _)
                    ( wX.varying p (≤⇒≤′ (m≤m⊔n k uj)) (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) (≤⇒≤′ (m≤m⊔n k' uj)) wx
                    , wY.fixed (≤⇒≤′ (m≤n⊔m k uj)) (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) (≤⇒≤′ (m≤n⊔m k' uj)) uy )) }) px)
          (elim-EquivOfS (CXY .Colimit.apex) (λ w → κ-fwd .func ((vk , vx) , w))
            (λ { {j , y} {j' , y'} (p' , wy) →
              EquivOf-intro
                ( ≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))
                , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) _ _)
                    ( wX.fixed (≤⇒≤′ (m≤m⊔n vk j)) (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) (≤⇒≤′ (m≤m⊔n vk j')) vx
                    , wY.varying p' (≤⇒≤′ (m≤n⊔m vk j)) (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) (≤⇒≤′ (m≤n⊔m vk j')) wy )) }) qy)

      forward : prod a b ⇒s CXY .Colimit.apex
      forward = κ-fwd ∘ prod-m ιX ιY

      -- The comparison maps intertwine the given cocones with the canonical ones.
      ι-coevalX : ∀ k → Category._≈_ 𝒮 (ιX ∘ cX .transf k) (canonX .Colimit.cocone .transf k)
      ι-coevalX = isX .IsColimit.colambda-coeval (canonX .Colimit.apex) (canonX .Colimit.cocone) .≃-NatTrans.transf-eq

      ι-coevalY : ∀ k → Category._≈_ 𝒮 (ιY ∘ cY .transf k) (canonY .Colimit.cocone .transf k)
      ι-coevalY = isY .IsColimit.colambda-coeval (canonY .Colimit.apex) (canonY .Colimit.cocone) .≃-NatTrans.transf-eq

      -- κ-fwd carries the product of the canonical cocones onto the product-chain cocone (its k-stage
      -- injection lands one diagonal step `k ⊔ k` up, which the chain absorbs).
      κ-cocone : ∀ k → Category._≈_ 𝒮 (κ-fwd ∘ prod-m (canonX .Colimit.cocone .transf k) (canonY .Colimit.cocone .transf k))
                                      (CXY .Colimit.cocone .transf k)
      κ-cocone k .func-eq {x₁ , y₁} {x₂ , y₂} (x₁≈x₂ , y₁≈y₂) =
        CXY .Colimit.apex .isEquivalence .sym
          (EquivOf-intro
            ( ≤⇒≤′ (m≤m⊔n k k)
            , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (m≤m⊔n k k)) x₂ y₂)
                ( Xc .Functor.fmor (≤⇒≤′ (m≤m⊔n k k)) .func-resp-≈ (X k .isEquivalence .sym x₁≈x₂)
                , Yc .Functor.fmor-cong {f₁ = ≤⇒≤′ (m≤m⊔n k k)} {f₂ = ≤⇒≤′ (m≤n⊔m k k)} tt
                    .func-eq (Y k .isEquivalence .sym y₁≈y₂) )))

      -- Hence `forward` is a cocone morphism from the product-chain cocone to the canonical apex.
      forward-cocone : ∀ k → Category._≈_ 𝒮 (forward ∘ prod-m (cX .transf k) (cY .transf k)) (CXY .Colimit.cocone .transf k)
      forward-cocone k =
        ≈-trans (assoc _ _ _)
        (≈-trans (∘-cong₂ (≈-sym (prod-m-comp ιX ιY (cX .transf k) (cY .transf k))))
        (≈-trans (∘-cong₂ (prod-m-cong (ι-coevalX k) (ι-coevalY k)))
                 (κ-cocone k)))

    ×-cocont : IsColimit (chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k))) (prod a b)
                         (step-cocone (λ k → prod-m (cX .transf k) (cY .transf k))
                                      (λ k → ≈-trans (prod-m-cong (cocone-step cX k) (cocone-step cY k))
                                                     (prod-m-comp (cX .transf (suc k)) (cY .transf (suc k)) (f k) (g k))))
    ×-cocont .IsColimit.colambda Z γ = CXY .Colimit.isColimit .IsColimit.colambda Z γ ∘ forward
    ×-cocont .IsColimit.colambda-cong α≃β =
      ∘-cong₁ (CXY .Colimit.isColimit .IsColimit.colambda-cong α≃β)
    ×-cocont .IsColimit.colambda-coeval Z γ .≃-NatTrans.transf-eq k =
      ≈-trans (assoc _ _ _)
      (≈-trans (∘-cong₂ (forward-cocone k))
               (CXY .Colimit.isColimit .IsColimit.colambda-coeval Z γ .≃-NatTrans.transf-eq k))
    ×-cocont .IsColimit.colambda-ext Z h = {!!}
