{-# OPTIONS --prop --postfix-projections --safe #-}

-- The cocompleteness structure of SetoidCat: initial object, strong coproducts, ω-colimits, and
-- cocontinuous products. This is the standalone half of the factorisation — instantiating colimit-mu-types
-- against it builds μ-types of polynomial functors on setoids (the index μ-types of the Fam construction).

open import Level using (_⊔_)
open import Data.Nat using (ℕ; suc; _≤′_; ≤′-refl)
open import Data.Product using (_,_; Σ)
open import Data.Sum using (inj₁; inj₂)
open import prop using (_,_; ∃)
open import categories
  using (Category; HasInitial; IsInitial; HasProducts; HasStrongCoproducts)
open import functor
  using (Functor; NatTrans; Colimit; IsColimit; constF; ≃-NatTrans; HasColimits)
open import omega-chains using (ω; chain; step-cocone; cocone-step)
open import prop-setoid
  using (Setoid; IsEquivalence; 𝟘; from-𝟘; from-𝟘-unique; +-setoid; ⊗-setoid; case; inject₁; inject₂;
         rel→Setoid; EquivOf-intro; rel-preserving-func)
  renaming (_⇒_ to _⇒s_; _≃m_ to _≈s_)
open import setoid-cat using (SetoidCat; Setoid-products)

open Setoid
open IsEquivalence
open _⇒s_
open _≈s_

module setoid-cat-colimits where

-- Work in SetoidCat o (o ⊔ e): the colimit's generated equality lands at level o ⊔ e, so the apex only fits
-- when the equality level absorbs the carrier level. The Fam index setoids (Setoid os (os ⊔ es)) are of this form.
module _ o e where
  private
    𝒮 = SetoidCat o (o ⊔ e)
  open Category 𝒮
  open HasInitial
  open IsInitial
  open HasStrongCoproducts

  initial : HasInitial 𝒮
  initial .witness = 𝟘
  initial .is-initial .from-initial = from-𝟘
  initial .is-initial .from-initial-ext f = from-𝟘-unique from-𝟘 f

  strongCoproducts : HasStrongCoproducts 𝒮 (Setoid-products o (o ⊔ e))
  strongCoproducts .coprod = +-setoid
  strongCoproducts .in₁ = inject₁
  strongCoproducts .in₂ = inject₂
  strongCoproducts .copair = case
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = f₁≈f₂ .func-eq (w≈ , x≈)
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = g₁≈g₂ .func-eq (w≈ , y≈)
  strongCoproducts .copair-in₁ f g .func-eq (w≈ , x≈) = f .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-in₂ f g .func-eq (w≈ , y≈) = g .func-resp-≈ (w≈ , y≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = h .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = h .func-resp-≈ (w≈ , y≈)

  -- Sequential colimit of a setoid ω-chain: pairs (n , x) with x in the n-th setoid, under the equivalence
  -- generated by identifying x with its image one (or more) steps up the chain.
  ωcolimits : HasColimits ω 𝒮
  ωcolimits D = colim
    where
    module D = Functor D
    A : Set o
    A = Σ ℕ (λ n → D.fobj n .Carrier)
    R : A → A → Prop (o ⊔ e)
    R (n , x) (m , y) = ∃ (n ≤′ m) (λ p → D.fobj m ._≈_ (D.fmor p .func x) y)
    apex : Setoid o (o ⊔ e)
    apex = rel→Setoid A R
    cocone : NatTrans D (constF ω apex)
    cocone .NatTrans.transf n .func x = n , x
    cocone .NatTrans.transf n .func-resp-≈ x≈ = EquivOf-intro (≤′-refl , D.fmor-id .func-eq x≈)
    cocone .NatTrans.natural p .func-eq a≈ = EquivOf-intro (p , D.fmor p .func-resp-≈ a≈)
    mediate : (X' : Setoid o (o ⊔ e)) → NatTrans D (constF ω X') → apex ⇒s X'
    mediate X' γ = rel-preserving-func X' f base
      where
      f : A → X' .Carrier
      f (n , a) = γ .NatTrans.transf n .func a
      base : ∀ {u v} → R u v → X' ._≈_ (f u) (f v)
      base {n , a} {m , b} (p , da≈b) =
        X' .isEquivalence .trans
          (γ .NatTrans.natural p .func-eq (D.fobj n .isEquivalence .refl))
          (γ .NatTrans.transf m .func-resp-≈ da≈b)
    colim : Colimit D
    colim .Colimit.apex = apex
    colim .Colimit.cocone = cocone
    colim .Colimit.isColimit .IsColimit.colambda = mediate
    colim .Colimit.isColimit .IsColimit.colambda-cong {X'} {α} α≈β .func-eq {n , a} {m , b} u≈v =
      X' .isEquivalence .trans
        (mediate X' α .func-resp-≈ u≈v)
        (α≈β .≃-NatTrans.transf-eq m .func-eq (D.fobj m .isEquivalence .refl))
    colim .Colimit.isColimit .IsColimit.colambda-coeval X' γ .≃-NatTrans.transf-eq n .func-eq a≈ =
      γ .NatTrans.transf n .func-resp-≈ a≈
    colim .Colimit.isColimit .IsColimit.colambda-ext X' f .func-eq {n , a} u≈v = f .func-resp-≈ u≈v

  open HasProducts (Setoid-products o (o ⊔ e)) using (prod; prod-m; prod-m-cong; prod-m-comp)
  open NatTrans using (transf)

  -- Finite products preserve ω-colimits: the product of two colimits is the colimit of the product chain.
  module _ {X Y : ℕ → obj} {f : ∀ k → X k ⇒ X (suc k)} {g : ∀ k → Y k ⇒ Y (suc k)} {a b : obj}
           {cX : NatTrans (chain {𝒞 = 𝒮} X f) (constF ω a)} {cY : NatTrans (chain {𝒞 = 𝒮} Y g) (constF ω b)}
           (isX : IsColimit (chain {𝒞 = 𝒮} X f) a cX) (isY : IsColimit (chain {𝒞 = 𝒮} Y g) b cY) where
    private
      CXY : Colimit (chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k)))
      CXY = ωcolimits (chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k)))
      canonX = ωcolimits (chain {𝒞 = 𝒮} X f)
      canonY = ωcolimits (chain {𝒞 = 𝒮} Y g)
      ιX : a ⇒s canonX .Colimit.apex
      ιX = isX .IsColimit.colambda (canonX .Colimit.apex) (canonX .Colimit.cocone)
      ιY : b ⇒s canonY .Colimit.apex
      ιY = isY .IsColimit.colambda (canonY .Colimit.apex) (canonY .Colimit.cocone)
      κ-fwd : prod (canonX .Colimit.apex) (canonY .Colimit.apex) ⇒s CXY .Colimit.apex
      κ-fwd = {!!}
      forward : prod a b ⇒s CXY .Colimit.apex
      forward = κ-fwd ∘ prod-m ιX ιY

    ×-cocont : IsColimit (chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k))) (prod a b)
                         (step-cocone (λ k → prod-m (cX .transf k) (cY .transf k))
                                      (λ k → ≈-trans (prod-m-cong (cocone-step cX k) (cocone-step cY k))
                                                     (prod-m-comp (cX .transf (suc k)) (cY .transf (suc k)) (f k) (g k))))
    ×-cocont .IsColimit.colambda Z γ = CXY .Colimit.isColimit .IsColimit.colambda Z γ ∘ forward
    ×-cocont .IsColimit.colambda-cong α≃β = {!!}
    ×-cocont .IsColimit.colambda-coeval Z γ = {!!}
    ×-cocont .IsColimit.colambda-ext Z h = {!!}
