{-# OPTIONS --prop --postfix-projections --safe #-}

-- The cocompleteness structure of SetoidCat: initial object, strong coproducts, ω-colimits, and
-- cocontinuous products. This is the standalone half of the factorisation — instantiating colimit-mu-types
-- against it builds μ-types of polynomial functors on setoids (the index μ-types of the Fam construction).

open import Level using (_⊔_)
open import Data.Nat using (ℕ; _≤′_; ≤′-refl)
open import Data.Product using (_,_; Σ)
open import Data.Sum using (inj₁; inj₂)
open import prop using (_,_; ∃)
open import categories
  using (Category; HasInitial; IsInitial; HasProducts; HasStrongCoproducts)
open import functor
  using (Functor; NatTrans; Colimit; IsColimit; constF; ≃-NatTrans; HasColimits)
open import omega-chains using (ω)
open import prop-setoid
  using (Setoid; IsEquivalence; 𝟘; from-𝟘; from-𝟘-unique; +-setoid; ⊗-setoid; case; inject₁; inject₂;
         rel→Setoid; EquivOf-intro; rel-preserving-func)
  renaming (_⇒_ to _⇒s_; _≃m_ to _≈s_)
open import setoid-cat using (SetoidCat; Setoid-products)

open Setoid
open IsEquivalence
open _⇒s_
open _≈s_

module setoid-cat-colimits where

-- Work in SetoidCat o (o ⊔ e): the colimit's generated equality lands at level o ⊔ e, so the apex only fits
-- when the equality level absorbs the carrier level. The Fam index setoids (Setoid os (os ⊔ es)) are of this form.
module _ o e where
  private
    𝒮 = SetoidCat o (o ⊔ e)
  open Category 𝒮
  open HasInitial
  open IsInitial
  open HasStrongCoproducts

  Setoid-initial : HasInitial 𝒮
  Setoid-initial .witness = 𝟘
  Setoid-initial .is-initial .from-initial = from-𝟘
  Setoid-initial .is-initial .from-initial-ext f = from-𝟘-unique from-𝟘 f

  Setoid-strongCoproducts : HasStrongCoproducts 𝒮 (Setoid-products o (o ⊔ e))
  Setoid-strongCoproducts .coprod = +-setoid
  Setoid-strongCoproducts .in₁ = inject₁
  Setoid-strongCoproducts .in₂ = inject₂
  Setoid-strongCoproducts .copair = case
  Setoid-strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = f₁≈f₂ .func-eq (w≈ , x≈)
  Setoid-strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = g₁≈g₂ .func-eq (w≈ , y≈)
  Setoid-strongCoproducts .copair-in₁ f g .func-eq (w≈ , x≈) = f .func-resp-≈ (w≈ , x≈)
  Setoid-strongCoproducts .copair-in₂ f g .func-eq (w≈ , y≈) = g .func-resp-≈ (w≈ , y≈)
  Setoid-strongCoproducts .copair-ext h .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = h .func-resp-≈ (w≈ , x≈)
  Setoid-strongCoproducts .copair-ext h .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = h .func-resp-≈ (w≈ , y≈)

  -- Sequential colimit of a setoid ω-chain: pairs (n , x) with x in the n-th setoid, under the equivalence
  -- generated by identifying x with its image one (or more) steps up the chain.
  Setoid-ωcolimits : HasColimits ω 𝒮
  Setoid-ωcolimits D = colim
    where
    module D = Functor D
    A : Set o
    A = Σ ℕ (λ n → D.fobj n .Carrier)
    R : A → A → Prop (o ⊔ e)
    R (n , x) (m , y) = ∃ (n ≤′ m) (λ p → D.fobj m ._≈_ (D.fmor p .func x) y)
    apex : Setoid o (o ⊔ e)
    apex = rel→Setoid A R
    cocone : NatTrans D (constF ω apex)
    cocone .NatTrans.transf n .func x = n , x
    cocone .NatTrans.transf n .func-resp-≈ x≈ = EquivOf-intro (≤′-refl , D.fmor-id .func-eq x≈)
    cocone .NatTrans.natural p .func-eq a≈ = EquivOf-intro (p , D.fmor p .func-resp-≈ a≈)
    mediate : (X' : Setoid o (o ⊔ e)) → NatTrans D (constF ω X') → apex ⇒s X'
    mediate X' γ = rel-preserving-func X' f base
      where
      f : A → X' .Carrier
      f (n , a) = γ .NatTrans.transf n .func a
      base : ∀ {u v} → R u v → X' ._≈_ (f u) (f v)
      base {n , a} {m , b} (p , da≈b) =
        X' .isEquivalence .trans
          (γ .NatTrans.natural p .func-eq (D.fobj n .isEquivalence .refl))
          (γ .NatTrans.transf m .func-resp-≈ da≈b)
    colim : Colimit D
    colim .Colimit.apex = apex
    colim .Colimit.cocone = cocone
    colim .Colimit.isColimit .IsColimit.colambda = mediate
    colim .Colimit.isColimit .IsColimit.colambda-cong {X'} {α} α≈β .func-eq {n , a} {m , b} u≈v =
      X' .isEquivalence .trans
        (mediate X' α .func-resp-≈ u≈v)
        (α≈β .≃-NatTrans.transf-eq m .func-eq (D.fobj m .isEquivalence .refl))
    colim .Colimit.isColimit .IsColimit.colambda-coeval X' γ .≃-NatTrans.transf-eq n .func-eq a≈ =
      γ .NatTrans.transf n .func-resp-≈ a≈
    colim .Colimit.isColimit .IsColimit.colambda-ext X' f .func-eq {n , a} u≈v = f .func-resp-≈ u≈v
