{-# OPTIONS --prop --postfix-projections --safe #-}

-- The cocompleteness structure of SetoidCat: initial object, strong coproducts, ω-colimits, and
-- cocontinuous products. This is the standalone half of the factorisation — instantiating colimit-mu-types
-- against it builds μ-types of polynomial functors on setoids (the index μ-types of the Fam construction).

open import Level using (_⊔_; lift)
open import Data.Nat using (ℕ; suc; _≤′_; ≤′-refl; ≤′-step) renaming (_⊔_ to _⊔ℕ_)
open import Data.Nat.Properties using (m≤m⊔n; m≤n⊔m; ≤⇒≤′; ≤′⇒≤; ⊔-monoˡ-≤; ⊔-monoʳ-≤)
open import Data.Product using (_,_; Σ)
open import Data.Sum using (inj₁; inj₂)
open import prop using (_,_; ∃; liftS; tt; proj₁; proj₂)
open import categories
  using (Category; HasInitial; IsInitial; HasProducts; HasStrongCoproducts)
open import functor
  using (Functor; NatTrans; Colimit; IsColimit; constF; constFmor; ≃-NatTrans; HasColimits; colambda-unique)
  renaming (_∘_ to _∘NT_)
open import omega-chains using (ω; chain; step-cocone; cocone-step)
open import prop-setoid
  using (Setoid; IsEquivalence; 𝟘; from-𝟘; from-𝟘-unique; +-setoid; ⊗-setoid; case; inject₁; inject₂;
         rel→Setoid; EquivOf-intro; rel-preserving-func; elim-EquivOfS)
  renaming (_⇒_ to _⇒s_; _≃m_ to _≈s_)
open import setoid-cat using (SetoidCat; Setoid-products)

open Setoid
open IsEquivalence
open _⇒s_
open _≈s_

module setoid-cat-colimits where

-- Work in SetoidCat o (o ⊔ e): the colimit's generated equality lands at level o ⊔ e, so the apex only fits
-- when the equality level absorbs the carrier level. The Fam index setoids (Setoid os (os ⊔ es)) are of this form.
module _ o e where
  private
    𝒮 = SetoidCat o (o ⊔ e)
  open Category 𝒮
  open HasInitial
  open IsInitial
  open HasStrongCoproducts

  initial : HasInitial 𝒮
  initial .witness = 𝟘
  initial .is-initial .from-initial = from-𝟘
  initial .is-initial .from-initial-ext f = from-𝟘-unique from-𝟘 f

  strongCoproducts : HasStrongCoproducts 𝒮 (Setoid-products o (o ⊔ e))
  strongCoproducts .coprod = +-setoid
  strongCoproducts .in₁ = inject₁
  strongCoproducts .in₂ = inject₂
  strongCoproducts .copair = case
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = f₁≈f₂ .func-eq (w≈ , x≈)
  strongCoproducts .copair-cong f₁≈f₂ g₁≈g₂ .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = g₁≈g₂ .func-eq (w≈ , y≈)
  strongCoproducts .copair-in₁ f g .func-eq (w≈ , x≈) = f .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-in₂ f g .func-eq (w≈ , y≈) = g .func-resp-≈ (w≈ , y≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₁ _} {_ , inj₁ _} (w≈ , x≈) = h .func-resp-≈ (w≈ , x≈)
  strongCoproducts .copair-ext h .func-eq {_ , inj₂ _} {_ , inj₂ _} (w≈ , y≈) = h .func-resp-≈ (w≈ , y≈)

  -- Sequential colimit of a setoid ω-chain: pairs (n , x) with x in the n-th setoid, under the equivalence
  -- generated by identifying x with its image one (or more) steps up the chain.
  ωcolimits : HasColimits ω 𝒮
  ωcolimits D = colim
    where
    module D = Functor D

    A : Set o
    A = Σ ℕ (λ n → D.fobj n .Carrier)

    R : A → A → Prop (o ⊔ e)
    R (n , x) (m , y) = ∃ (n ≤′ m) (λ p → D.fobj m ._≈_ (D.fmor p .func x) y)

    apex : Setoid o (o ⊔ e)
    apex = rel→Setoid A R

    cocone : NatTrans D (constF ω apex)
    cocone .NatTrans.transf n .func x = n , x
    cocone .NatTrans.transf n .func-resp-≈ x≈ = EquivOf-intro (≤′-refl , D.fmor-id .func-eq x≈)
    cocone .NatTrans.natural p .func-eq a≈ = EquivOf-intro (p , D.fmor p .func-resp-≈ a≈)

    mediate : (X' : Setoid o (o ⊔ e)) → NatTrans D (constF ω X') → apex ⇒s X'
    mediate X' γ = rel-preserving-func X' f base
      where
      f : A → X' .Carrier
      f (n , a) = γ .NatTrans.transf n .func a

      base : ∀ {u v} → R u v → X' ._≈_ (f u) (f v)
      base {n , a} {m , b} (p , da≈b) =
        X' .isEquivalence .trans
          (γ .NatTrans.natural p .func-eq (D.fobj n .isEquivalence .refl))
          (γ .NatTrans.transf m .func-resp-≈ da≈b)

    colim : Colimit D
    colim .Colimit.apex = apex
    colim .Colimit.cocone = cocone
    colim .Colimit.isColimit .IsColimit.colambda = mediate
    colim .Colimit.isColimit .IsColimit.colambda-cong {X'} {α} α≈β .func-eq {n , a} {m , b} u≈v =
      X' .isEquivalence .trans
        (mediate X' α .func-resp-≈ u≈v)
        (α≈β .≃-NatTrans.transf-eq m .func-eq (D.fobj m .isEquivalence .refl))
    colim .Colimit.isColimit .IsColimit.colambda-coeval X' γ .≃-NatTrans.transf-eq n .func-eq a≈ =
      γ .NatTrans.transf n .func-resp-≈ a≈
    colim .Colimit.isColimit .IsColimit.colambda-ext X' f .func-eq {n , a} u≈v = f .func-resp-≈ u≈v

  open HasProducts (Setoid-products o (o ⊔ e)) using (prod; prod-m; prod-m-cong; prod-m-comp; prod-m-id)
  open NatTrans using (transf)

  -- Finite products preserve ω-colimits: the product of two colimits is the colimit of the product chain.
  module _ {X Y : ℕ → obj} {f : ∀ k → X k ⇒ X (suc k)} {g : ∀ k → Y k ⇒ Y (suc k)} {a b : obj}
           {cX : NatTrans (chain {𝒞 = 𝒮} X f) (constF ω a)} {cY : NatTrans (chain {𝒞 = 𝒮} Y g) (constF ω b)}
           (isX : IsColimit (chain {𝒞 = 𝒮} X f) a cX) (isY : IsColimit (chain {𝒞 = 𝒮} Y g) b cY) where
    private
      Xc  = chain {𝒞 = 𝒮} X f
      Yc  = chain {𝒞 = 𝒮} Y g
      PXY = chain {𝒞 = 𝒮} (λ k → prod (X k) (Y k)) (λ k → prod-m (f k) (g k))

      CXY : Colimit PXY
      CXY = ωcolimits PXY

      canonX = ωcolimits Xc
      canonY = ωcolimits Yc

      ιX : a ⇒s canonX .Colimit.apex
      ιX = isX .IsColimit.colambda (canonX .Colimit.apex) (canonX .Colimit.cocone)

      ιY : b ⇒s canonY .Colimit.apex
      ιY = isY .IsColimit.colambda (canonY .Colimit.apex) (canonY .Colimit.cocone)

      cocone₀ : NatTrans PXY (constF ω (prod a b))
      cocone₀ = step-cocone (λ k → prod-m (cX .transf k) (cY .transf k))
                            (λ k → ≈-trans (prod-m-cong (cocone-step cX k) (cocone-step cY k))
                                           (prod-m-comp (cX .transf (suc k)) (cY .transf (suc k)) (f k) (g k)))

      -- Two walks with the same endpoints agree; `varying` additionally absorbs a single-step shift of
      -- the source through the chain.
      module walks (D : Functor ω 𝒮) where
        private
          module D = Functor D

        fixed : ∀ {k M N} (low : k ≤′ M) (mid : M ≤′ N) (hi : k ≤′ N) (a : D.fobj k .Carrier) →
                D.fobj N ._≈_ (D.fmor mid .func (D.fmor low .func a)) (D.fmor hi .func a)
        fixed low mid hi a =
          D.fobj _ .isEquivalence .trans
            (D.fobj _ .isEquivalence .sym (D.fmor-comp mid low .func-eq (D.fobj _ .isEquivalence .refl)))
            (D.fmor-cong tt .func-eq (D.fobj _ .isEquivalence .refl))

        varying : ∀ {k k' M N} (p : k ≤′ k') (low : k ≤′ M) (mid : M ≤′ N) (hi : k' ≤′ N)
                  {a : D.fobj k .Carrier} {a' : D.fobj k' .Carrier} →
                  D.fobj k' ._≈_ (D.fmor p .func a) a' →
                  D.fobj N ._≈_ (D.fmor mid .func (D.fmor low .func a)) (D.fmor hi .func a')
        varying p low mid hi wa =
          D.fobj _ .isEquivalence .trans
            (D.fobj _ .isEquivalence .sym (D.fmor-comp mid low .func-eq (D.fobj _ .isEquivalence .refl)))
          (D.fobj _ .isEquivalence .trans
            (D.fmor-cong tt .func-eq (D.fobj _ .isEquivalence .refl))
          (D.fobj _ .isEquivalence .trans
            (D.fmor-comp hi p .func-eq (D.fobj _ .isEquivalence .refl))
            (D.fmor hi .func-resp-≈ wa)))

      module wX = walks Xc
      module wY = walks Yc

      -- The product chain's transport is the pairing of the component transports.
      prod-walk : ∀ {m n} (qw : m ≤′ n) (a : X m .Carrier) (b : Y m .Carrier) →
                  prod (X n) (Y n) ._≈_ (PXY .Functor.fmor qw .func (a , b))
                                         (Xc .Functor.fmor qw .func a , Yc .Functor.fmor qw .func b)
      prod-walk ≤′-refl      a b = prod (X _) (Y _) .isEquivalence .refl
      prod-walk (≤′-step qw) a b .proj₁ = f _ .func-resp-≈ (prod-walk qw a b .proj₁)
      prod-walk (≤′-step qw) a b .proj₂ = g _ .func-resp-≈ (prod-walk qw a b .proj₂)

      κ-fwd : prod (canonX .Colimit.apex) (canonY .Colimit.apex) ⇒s CXY .Colimit.apex
      κ-fwd .func ((k , x) , (j , y)) =
        _ , (Xc .Functor.fmor (≤⇒≤′ (m≤m⊔n k j)) .func x , Yc .Functor.fmor (≤⇒≤′ (m≤n⊔m k j)) .func y)
      κ-fwd .func-resp-≈ {u₁ , (uj , uy)} {(vk , vx) , v₂} (liftS px , liftS qy) =
        CXY .Colimit.apex .isEquivalence .trans
          (elim-EquivOfS (CXY .Colimit.apex) (λ w → κ-fwd .func (w , (uj , uy)))
            (λ { {k , x} {k' , x'} (p , wx) →
              EquivOf-intro
                ( ≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))
                , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) _ _)
                    ( wX.varying p (≤⇒≤′ (m≤m⊔n k uj)) (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) (≤⇒≤′ (m≤m⊔n k' uj)) wx
                    , wY.fixed (≤⇒≤′ (m≤n⊔m k uj)) (≤⇒≤′ (⊔-monoˡ-≤ uj (≤′⇒≤ p))) (≤⇒≤′ (m≤n⊔m k' uj)) uy )) }) px)
          (elim-EquivOfS (CXY .Colimit.apex) (λ w → κ-fwd .func ((vk , vx) , w))
            (λ { {j , y} {j' , y'} (p' , wy) →
              EquivOf-intro
                ( ≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))
                , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) _ _)
                    ( wX.fixed (≤⇒≤′ (m≤m⊔n vk j)) (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) (≤⇒≤′ (m≤m⊔n vk j')) vx
                    , wY.varying p' (≤⇒≤′ (m≤n⊔m vk j)) (≤⇒≤′ (⊔-monoʳ-≤ vk (≤′⇒≤ p'))) (≤⇒≤′ (m≤n⊔m vk j')) wy )) }) qy)

      forward : prod a b ⇒s CXY .Colimit.apex
      forward = κ-fwd ∘ prod-m ιX ιY

      -- The comparison maps intertwine the given cocones with the canonical ones.
      ι-coevalX : ∀ k → Category._≈_ 𝒮 (ιX ∘ cX .transf k) (canonX .Colimit.cocone .transf k)
      ι-coevalX = isX .IsColimit.colambda-coeval (canonX .Colimit.apex) (canonX .Colimit.cocone) .≃-NatTrans.transf-eq

      ι-coevalY : ∀ k → Category._≈_ 𝒮 (ιY ∘ cY .transf k) (canonY .Colimit.cocone .transf k)
      ι-coevalY = isY .IsColimit.colambda-coeval (canonY .Colimit.apex) (canonY .Colimit.cocone) .≃-NatTrans.transf-eq

      -- κ-fwd carries the product of the canonical cocones onto the product-chain cocone (its k-stage
      -- injection lands one diagonal step `k ⊔ k` up, which the chain absorbs).
      κ-cocone : ∀ k → Category._≈_ 𝒮 (κ-fwd ∘ prod-m (canonX .Colimit.cocone .transf k) (canonY .Colimit.cocone .transf k))
                                      (CXY .Colimit.cocone .transf k)
      κ-cocone k .func-eq {x₁ , y₁} {x₂ , y₂} (x₁≈x₂ , y₁≈y₂) =
        CXY .Colimit.apex .isEquivalence .sym
          (EquivOf-intro
            ( ≤⇒≤′ (m≤m⊔n k k)
            , prod (X _) (Y _) .isEquivalence .trans (prod-walk (≤⇒≤′ (m≤m⊔n k k)) x₂ y₂)
                ( Xc .Functor.fmor (≤⇒≤′ (m≤m⊔n k k)) .func-resp-≈ (X k .isEquivalence .sym x₁≈x₂)
                , Yc .Functor.fmor-cong {f₁ = ≤⇒≤′ (m≤m⊔n k k)} {f₂ = ≤⇒≤′ (m≤n⊔m k k)} tt
                    .func-eq (Y k .isEquivalence .sym y₁≈y₂) )))

      -- Hence `forward` is a cocone morphism from the product-chain cocone to the canonical apex.
      forward-cocone : ∀ k → Category._≈_ 𝒮 (forward ∘ prod-m (cX .transf k) (cY .transf k)) (CXY .Colimit.cocone .transf k)
      forward-cocone k =
        ≈-trans (assoc _ _ _)
        (≈-trans (∘-cong₂ (≈-sym (prod-m-comp ιX ιY (cX .transf k) (cY .transf k))))
        (≈-trans (∘-cong₂ (prod-m-cong (ι-coevalX k) (ι-coevalY k)))
                 (κ-cocone k)))

      -- The comparison maps are isos; their inverses mediate the canonical colimits back to a, b.
      ι⁻X : canonX .Colimit.apex ⇒s a
      ι⁻X = canonX .Colimit.isColimit .IsColimit.colambda a cX

      ι⁻Y : canonY .Colimit.apex ⇒s b
      ι⁻Y = canonY .Colimit.isColimit .IsColimit.colambda b cY

      ι⁻X-coeval : ∀ k → Category._≈_ 𝒮 (ι⁻X ∘ canonX .Colimit.cocone .transf k) (cX .transf k)
      ι⁻X-coeval = canonX .Colimit.isColimit .IsColimit.colambda-coeval a cX .≃-NatTrans.transf-eq

      ι⁻Y-coeval : ∀ k → Category._≈_ 𝒮 (ι⁻Y ∘ canonY .Colimit.cocone .transf k) (cY .transf k)
      ι⁻Y-coeval = canonY .Colimit.isColimit .IsColimit.colambda-coeval b cY .≃-NatTrans.transf-eq

      ιinvX : Category._≈_ 𝒮 (ι⁻X ∘ ιX) (id a)
      ιinvX = colambda-unique isX (λ k →
        ≈-trans (assoc ι⁻X ιX (cX .transf k))
        (≈-trans (∘-cong₂ (ι-coevalX k))
        (≈-trans (ι⁻X-coeval k) (≈-sym id-left))))

      ιinvY : Category._≈_ 𝒮 (ι⁻Y ∘ ιY) (id b)
      ιinvY = colambda-unique isY (λ k →
        ≈-trans (assoc ι⁻Y ιY (cY .transf k))
        (≈-trans (∘-cong₂ (ι-coevalY k))
        (≈-trans (ι⁻Y-coeval k) (≈-sym id-left))))

      -- κ-bwd splits κ-fwd: it sends a stage-n product back to the diagonal pair of injections.
      ρ : NatTrans PXY (constF ω (prod (canonX .Colimit.apex) (canonY .Colimit.apex)))
      ρ = step-cocone (λ k → prod-m (canonX .Colimit.cocone .transf k) (canonY .Colimit.cocone .transf k))
                      (λ k → ≈-trans (prod-m-cong (cocone-step (canonX .Colimit.cocone) k)
                                                  (cocone-step (canonY .Colimit.cocone) k))
                                     (prod-m-comp (canonX .Colimit.cocone .transf (suc k))
                                                  (canonY .Colimit.cocone .transf (suc k)) (f k) (g k)))

      κ-bwd : CXY .Colimit.apex ⇒s prod (canonX .Colimit.apex) (canonY .Colimit.apex)
      κ-bwd = CXY .Colimit.isColimit .IsColimit.colambda (prod (canonX .Colimit.apex) (canonY .Colimit.apex)) ρ

      κ-bwd-coeval : ∀ k → Category._≈_ 𝒮 (κ-bwd ∘ CXY .Colimit.cocone .transf k)
                                          (prod-m (canonX .Colimit.cocone .transf k) (canonY .Colimit.cocone .transf k))
      κ-bwd-coeval =
        CXY .Colimit.isColimit .IsColimit.colambda-coeval
          (prod (canonX .Colimit.apex) (canonY .Colimit.apex)) ρ .≃-NatTrans.transf-eq

      κ-bwd∘fwd : Category._≈_ 𝒮 (κ-bwd ∘ κ-fwd) (id (prod (canonX .Colimit.apex) (canonY .Colimit.apex)))
      κ-bwd∘fwd .func-eq {(k , x) , (j , y)} {(k' , x') , (j' , y')} (ex , ey) =
        ( canonX .Colimit.apex .isEquivalence .trans
            (canonX .Colimit.apex .isEquivalence .sym
              (EquivOf-intro (≤⇒≤′ (m≤m⊔n k j) , X (k ⊔ℕ j) .isEquivalence .refl)))
            ex
        , canonY .Colimit.apex .isEquivalence .trans
            (canonY .Colimit.apex .isEquivalence .sym
              (EquivOf-intro (≤⇒≤′ (m≤n⊔m k j) , Y (k ⊔ℕ j) .isEquivalence .refl)))
            ey )

      backward : prod (canonX .Colimit.apex) (canonY .Colimit.apex) ⇒s prod a b
      backward = prod-m ι⁻X ι⁻Y

      -- `backward ∘ κ-bwd` is a section of `forward`.
      retract : Category._≈_ 𝒮 ((backward ∘ κ-bwd) ∘ forward) (id (prod a b))
      retract =
        ≈-trans (assoc backward κ-bwd forward)
        (≈-trans (∘-cong₂ (≈-trans (≈-sym (assoc κ-bwd κ-fwd (prod-m ιX ιY)))
                          (≈-trans (∘-cong₁ κ-bwd∘fwd) id-left)))
        (≈-trans (≈-sym (prod-m-comp ι⁻X ι⁻Y ιX ιY))
        (≈-trans (prod-m-cong ιinvX ιinvY) prod-m-id)))

      retract-cocone : ∀ k → Category._≈_ 𝒮 ((backward ∘ κ-bwd) ∘ CXY .Colimit.cocone .transf k)
                                            (prod-m (cX .transf k) (cY .transf k))
      retract-cocone k =
        ≈-trans (assoc backward κ-bwd (CXY .Colimit.cocone .transf k))
        (≈-trans (∘-cong₂ (κ-bwd-coeval k))
        (≈-trans (≈-sym (prod-m-comp ι⁻X ι⁻Y (canonX .Colimit.cocone .transf k) (canonY .Colimit.cocone .transf k)))
                 (prod-m-cong (ι⁻X-coeval k) (ι⁻Y-coeval k))))

    ×-cocont : IsColimit PXY (prod a b) cocone₀
    ×-cocont .IsColimit.colambda Z γ = CXY .Colimit.isColimit .IsColimit.colambda Z γ ∘ forward
    ×-cocont .IsColimit.colambda-cong α≃β =
      ∘-cong₁ (CXY .Colimit.isColimit .IsColimit.colambda-cong α≃β)
    ×-cocont .IsColimit.colambda-coeval Z γ .≃-NatTrans.transf-eq k =
      ≈-trans (assoc _ _ _)
      (≈-trans (∘-cong₂ (forward-cocone k))
               (CXY .Colimit.isColimit .IsColimit.colambda-coeval Z γ .≃-NatTrans.transf-eq k))
    ×-cocont .IsColimit.colambda-ext Z h =
      ≈-trans (∘-cong₁ lemA)
      (≈-trans (assoc h (backward ∘ κ-bwd) forward)
      (≈-trans (∘-cong₂ retract) id-right))
      where
        lemA : Category._≈_ 𝒮 (CXY .Colimit.isColimit .IsColimit.colambda Z (constFmor h ∘NT cocone₀))
                              (h ∘ (backward ∘ κ-bwd))
        lemA = colambda-unique (CXY .Colimit.isColimit) (λ k →
          ≈-trans (CXY .Colimit.isColimit .IsColimit.colambda-coeval Z (constFmor h ∘NT cocone₀) .≃-NatTrans.transf-eq k)
          (≈-sym (≈-trans (assoc h (backward ∘ κ-bwd) (CXY .Colimit.cocone .transf k))
                          (∘-cong₂ (retract-cocone k)))))

  -- A product with the initial (empty) setoid is itself initial: a pair needs a 𝟘 element, so the
  -- carrier is empty.
  prod𝟘-initial : ∀ {Γ} → IsInitial 𝒮 (prod Γ 𝟘)
  prod𝟘-initial .from-initial .func (_ , lift ())
  prod𝟘-initial .from-initial .func-resp-≈ {_ , lift ()}
  prod𝟘-initial .from-initial-ext f .func-eq {_ , lift ()}
